# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-01-06 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0003_auto_20210106_0200'),
        ('importexport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imProducts', to='ERP.Division'),
        ),
    ]
