# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-01-06 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importexport', '0002_products_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='invoiceNumber',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
