# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-01-08 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importexport', '0003_auto_20210106_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialissue',
            name='stock',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
