# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-01-10 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('importexport', '0004_auto_20210108_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintmanagement',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lastnamee', to='ERP.service'),
        ),
    ]
