# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-01-11 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importexport', '0005_auto_20210110_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintmanagement',
            name='comm_nr',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
