# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-13 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0011_merge_20210111_1745'),
        ('importexport', '0006_complaintmanagement_comm_nr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintmanagement',
            name='comm_nr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='comm_nr',
            field=models.CharField(blank=True, default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='projects',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='projects',
            unique_together=set([('title', 'comm_nr', 'division')]),
        ),
    ]
