# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-01-22 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importexport', '0009_auto_20210122_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='machinemodel',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
