# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-01-25 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importexport', '0010_invoice_machinemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintmanagement',
            name='complaintRef',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
