# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-03-22 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importexport', '0011_auto_20210125_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='poNumber',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
