# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-01-08 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='icon',
            field=models.ImageField(null=True, upload_to=projects.models.getIconPath),
        ),
    ]
