# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-03-30 05:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_auto_20210107_0704'),
        ('projects', '0003_auto_20210111_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='notes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectNotes', to='notes.notebook'),
        ),
    ]
