# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-03-30 06:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='notes',
        ),
    ]
