# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-03 08:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ERP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyHolidays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(null=True)),
                ('typ', models.CharField(choices=[('national', 'national'), ('state', 'state'), ('restricted', 'restricted')], default='national', max_length=20)),
                ('name', models.CharField(max_length=50, null=True)),
                ('division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holidaysdivisions', to='ERP.Division')),
            ],
        ),
        migrations.CreateModel(
            name='HomeChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('type', models.CharField(choices=[('Chart', 'Chart'), ('Report', 'Report')], default='Chart', max_length=30)),
                ('index', models.PositiveIntegerField(default=1, null=True)),
                ('chartType', models.CharField(choices=[('Pie', 'Pie'), ('Bar', 'Bar'), ('Line', 'Line'), ('Doughnut', 'Doughnut'), ('Table', 'Table')], default='Bar', max_length=30)),
                ('enabled', models.BooleanField(default=False)),
                ('configuration', models.CharField(max_length=3000, null=True)),
                ('query', models.TextField(max_length=10000, null=True)),
                ('division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activeDivision', to='ERP.Division')),
            ],
        ),
    ]
