# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-13 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_auto_20210113_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Selected', 'Selected')], default='Created', max_length=30),
        ),
    ]
