# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-19 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_auto_20210113_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='isSelected',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Shortlisted', 'Shortlisted'), ('Selected', 'Selected'), ('Rejected', 'Rejected')], default='Created', max_length=30),
        ),
    ]
