# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-20 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_auto_20210119_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='ctc',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
