# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-03 08:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import website.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Components',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('component_type', models.CharField(max_length=250, null=True)),
                ('data', models.TextField(max_length=10000, null=True)),
                ('template', models.TextField(default='', max_length=100000)),
                ('index', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('url', models.CharField(max_length=250)),
                ('title', models.CharField(default='No Title', max_length=250, null=True)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('ogImage', models.FileField(null=True, upload_to=website.models.getSampleImagePath)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UIelementTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('defaultData', models.TextField(max_length=10000, null=True)),
                ('template', models.TextField(max_length=100000, null=True)),
                ('name', models.CharField(max_length=250)),
                ('sampleImg', models.FileField(null=True, upload_to=website.models.getSampleImagePath)),
                ('mobilePreview', models.FileField(null=True, upload_to=website.models.getSampleImagePath)),
                ('live', models.BooleanField(default=False)),
                ('templateCategory', models.CharField(choices=[('Contact Us', 'Contact Us'), ('Introduction', 'Introduction'), ('Image List', 'Image List'), ('Info Section', 'Info Section'), ('Testimonials', 'Testimonials'), ('Widgets', 'Widgets'), ('Header', 'Header'), ('Footer', 'Footer'), ('Others', 'Others')], max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='components',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='website.Page'),
        ),
    ]
