# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-02-04 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='enableChat',
            field=models.BooleanField(default=False),
        ),
    ]
