# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-02-10 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_uielementtemplate_css'),
    ]

    operations = [
        migrations.AddField(
            model_name='uielementtemplate',
            name='images',
            field=models.TextField(max_length=10000, null=True),
        ),
    ]
