# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-02-11 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_uielementtemplate_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='components',
            name='css',
            field=models.TextField(max_length=100000, null=True),
        ),
    ]
