# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-02-18 12:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_components_css'),
    ]

    operations = [
        migrations.AlterField(
            model_name='components',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='components', to='website.Page'),
        ),
    ]
