# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-02-19 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20210218_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
