# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-02-24 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20210219_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='components',
            name='data',
            field=models.TextField(null=True),
        ),
    ]
