# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-19 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20210224_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='inFooter',
            field=models.BooleanField(default=False),
        ),
    ]
