# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-07 07:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Invoice',
            new_name='Expense',
        ),
    ]
