# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-07 09:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0004_auto_20210107_0705'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0002_auto_20210107_0753'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceQty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('product', models.CharField(max_length=100, null=True)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('price', models.FloatField(default=1)),
                ('taxCode', models.CharField(max_length=100, null=True)),
                ('taxPer', models.FloatField(null=True)),
                ('tax', models.FloatField(null=True)),
                ('total', models.FloatField(null=True)),
                ('receivedQty', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceReceived',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('created', 'created'), ('Sent', 'Sent'), ('GRN', 'GRN'), ('Approved', 'Approved'), ('paid', 'paid'), ('rejected', 'rejected')], default='created', max_length=30)),
                ('companyName', models.CharField(max_length=100, null=True)),
                ('personName', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('address', models.TextField(max_length=200, null=True)),
                ('pincode', models.CharField(max_length=10, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('country', models.CharField(max_length=30, null=True)),
                ('deliveryDate', models.DateField(blank=True, null=True)),
                ('paymentDueDate', models.DateField(null=True)),
                ('gstIn', models.CharField(max_length=30, null=True)),
                ('accNo', models.CharField(max_length=30, null=True)),
                ('ifsc', models.CharField(max_length=30, null=True)),
                ('bankName', models.CharField(max_length=30, null=True)),
                ('invNo', models.CharField(max_length=50, null=True)),
                ('totalAmount', models.FloatField(default=0)),
                ('balanceAmount', models.FloatField(default=0)),
                ('paidAmount', models.FloatField(default=0)),
                ('note', models.TextField(max_length=500, null=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoiceAccount', to='finance.Account')),
                ('companyReference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoiceCompany', to='ERP.service')),
                ('costcenter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoiceCostcenter', to='finance.CostCenter')),
                ('division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoiceDivision', to='ERP.Division')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoiceUsers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='invoiceqty',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parentInvoice', to='finance.InvoiceReceived'),
        ),
    ]
