# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-08 08:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20210107_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuretermsandconditions',
            name='division',
        ),
        migrations.DeleteModel(
            name='ConfigureTermsAndConditions',
        ),
    ]
