# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-08 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0005_auto_20210107_1808'),
        ('finance', '0004_auto_20210108_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursal',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='divisionDisbursal', to='ERP.Division'),
        ),
    ]
