# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-09 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_disbursal_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='termsandconditions',
            name='counter',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='termsandconditions',
            name='prefix',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
