# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-09 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_auto_20210109_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='uniqueId',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
