# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-09 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_termsandconditions_typ'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicereceived',
            name='invType',
            field=models.CharField(choices=[('INVOICE', 'INVOICE'), ('EXPENSES', 'EXPENSES')], default='INVOICE', max_length=30),
        ),
    ]
