# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-09 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import finance.models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_invoicereceived_invtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceqty',
            name='qty',
        ),
        migrations.AddField(
            model_name='invoiceqty',
            name='attachment',
            field=models.FileField(null=True, upload_to=finance.models.getInvoicesPath),
        ),
        migrations.AddField(
            model_name='invoiceqty',
            name='description',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
