# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-09 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_auto_20210109_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicereceived',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
