# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-09 13:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0012_invoicereceived_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceqty',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoiceQtyUsers', to=settings.AUTH_USER_MODEL),
        ),
    ]
