# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-11 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_invoiceqty_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicereceived',
            name='uniqueId',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
