# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-20 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_invoicereceived_uniqueid'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='billingAddress',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='billingCity',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='billingCountry',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='billingPincode',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='billingState',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='sameasbilling',
            field=models.BooleanField(default=False),
        ),
    ]
