# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-11 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_auto_20210120_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='tds',
            field=models.FloatField(default=0),
        ),
    ]
