# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-23 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientRelationships', '0018_auto_20210222_0801'),
        ('finance', '0016_transaction_tds'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('qty', models.PositiveIntegerField(default=0)),
                ('price', models.FloatField(default=1)),
                ('total', models.FloatField(default=1)),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='clientRelationships.Contact')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='finance.Inventory')),
            ],
        ),
    ]
