# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-01 10:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0061_auto_20210222_0830'),
        ('clientRelationships', '0019_contactauth'),
        ('finance', '0018_cart_division'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together=set([('division', 'contact', 'product')]),
        ),
    ]
