# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-01 10:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientRelationships', '0019_contactauth'),
        ('finance', '0019_auto_20210301_1017'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together=set([('contact', 'product')]),
        ),
    ]
