# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-08 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0020_auto_20210301_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='addonsData',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='customizationData',
            field=models.TextField(max_length=10000, null=True),
        ),
    ]
