# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-08 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0021_auto_20210308_0448'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='addon',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='customisation',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
