# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-01-06 02:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ERP', '0002_auto_20210105_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together=set([('name', 'user')]),
        ),
    ]
