# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-07 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0004_auto_20210107_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='dueDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='division',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='division',
            name='totalDue',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
