# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-11 04:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ERP', '0007_auto_20210109_0639'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(default=0)),
                ('notificationCount', models.PositiveIntegerField(default=0)),
                ('locked', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userApps', to='ERP.application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menuapps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
