# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-11 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0007_auto_20210109_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='hospPatientInBillCounter',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='division',
            name='hospPatientInCounter',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='division',
            name='hospPatientOutBillCounter',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='division',
            name='hospPatientOutCounter',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='division',
            name='hospPrefix',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='division',
            name='hospUHIDCounter',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
