# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-11 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0008_auto_20210111_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='hospPatientCounter',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
