# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-11 11:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0009_division_hosppatientcounter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='division',
            name='hospPrefix',
        ),
    ]
