# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-11 17:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0010_remove_division_hospprefix'),
        ('ERP', '0009_auto_20210111_1559'),
    ]

    operations = [
    ]
