# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-20 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0011_merge_20210111_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='accountNumber',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='bankName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='ifscCode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
