# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-26 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0012_auto_20210120_0847'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageBilling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('title', models.CharField(max_length=500)),
                ('amount', models.FloatField(default=0, null=True)),
                ('month', models.CharField(blank=True, max_length=50, null=True)),
                ('year', models.CharField(blank=True, max_length=50, null=True)),
                ('division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billingdivisions', to='ERP.Division')),
            ],
        ),
    ]
