# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-28 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0013_usagebilling'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=500)),
                ('value', models.TextField(max_length=1000)),
            ],
        ),
    ]
