# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-28 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0014_languagetranslation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarSlots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('slot', models.CharField(max_length=500)),
                ('date', models.DateField(null=True)),
                ('description', models.CharField(max_length=500)),
                ('is_available', models.BooleanField(default=False)),
            ],
        ),
    ]
