# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-28 07:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ERP', '0015_calendarslots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarslots',
            name='date',
        ),
        migrations.RemoveField(
            model_name='calendarslots',
            name='description',
        ),
        migrations.AddField(
            model_name='calendarslots',
            name='day',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='calendarslots',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendarSlotsUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='calendarslots',
            name='slot',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
