# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-01-29 09:56
from __future__ import unicode_literals

import ERP.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0016_auto_20210128_0705'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='usagebilling',
        #     name='app',
        #     field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='usagebillings', to='ERP.application'),
        # ),
        # migrations.AddField(
        #     model_name='usagebilling',
        #     name='description',
        #     field=models.CharField(max_length=250, null=True),
        # ),
        # migrations.AddField(
        #     model_name='usagebilling',
        #     name='icon',
        #     field=models.FileField(null=True, upload_to=ERP.models.getDivisionLogoAttachmentPath),
        # ),
    ]
