# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-01-29 10:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0017_auto_20210129_0956'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='usagebilling',
        #     name='app',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usagebillings', to='ERP.application'),
        # ),
    ]
