# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-01-29 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0018_auto_20210129_1018'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='usagebilling',
        #     name='app',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usagebillings', to='ERP.application'),
        # ),
        # migrations.AddField(
        #     model_name='usagebilling',
        #     name='description',
        #     field=models.CharField(max_length=250, null=True),
        # ),
        # migrations.AddField(
        #     model_name='usagebilling',
        #     name='icon',
        #     field=models.CharField(max_length=250, null=True),
        # ),
    ]
