# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-03 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0028_auto_20210203_0845'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='languagetranslation',
        #     name='lang',
        #     field=models.CharField(max_length=500, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='languagetranslation',
        #     name='key',
        #     field=models.CharField(max_length=500, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='languagetranslation',
        #     name='value',
        #     field=models.TextField(max_length=1000, null=True),
        # ),
    ]
