# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-02-05 05:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0031_auto_20210204_0557'),
    ]

    operations = [
        migrations.AddField(
            model_name='languagetranslation',
            name='lang',
            field=models.CharField(max_length=500, null=True),
        ),
        # migrations.AddField(
        #     model_name='usagebilling',
        #     name='app',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usagebillings', to='ERP.application'),
        # ),
        # migrations.AddField(
        #     model_name='usagebilling',
        #     name='description',
        #     field=models.CharField(max_length=250, null=True),
        # ),
        # migrations.AddField(
        #     model_name='usagebilling',
        #     name='icon',
        #     field=models.CharField(max_length=250, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='languagetranslation',
        #     name='key',
        #     field=models.CharField(max_length=500, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='languagetranslation',
        #     name='value',
        #     field=models.TextField(max_length=1000, null=True),
        # ),
    ]
