# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-05 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0033_auto_20210205_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinepaymentdetails',
            name='refId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
