# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-06 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0033_merge_20210205_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlinePaymentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('payId', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.FloatField(default=0, null=True)),
                ('refId', models.CharField(blank=True, max_length=50, null=True)),
                ('paymentGatewayType', models.CharField(blank=True, max_length=50, null=True)),
                ('is_success', models.BooleanField(default=False)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='usagebilling',
            name='app',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usagebillings', to='ERP.application'),
        ),
        migrations.AddField(
            model_name='usagebilling',
            name='description',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='usagebilling',
            name='icon',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
