# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-05 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0034_onlinepaymentdetails_refid'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinepaymentdetails',
            name='is_success',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='onlinepaymentdetails',
            name='paymentGatewayType',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
