# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-06 08:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0034_auto_20210206_0824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlinepaymentdetails',
            name='source',
        ),
    ]
