# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-06 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0036_onlinepaymentdetails_source'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='onlinepaymentdetails',
        #     name='chatUid',
        #     field=models.CharField(blank=True, max_length=50, null=True),
        # ),
    ]
