# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-06 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0037_onlinepaymentdetails_chatuid'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='onlinepaymentdetails',
        #     name='failureUrl',
        #     field=models.CharField(blank=True, max_length=50, null=True),
        # ),
        # migrations.AddField(
        #     model_name='onlinepaymentdetails',
        #     name='successUrl',
        #     field=models.CharField(blank=True, max_length=50, null=True),
        # ),
    ]
