# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-06 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0038_auto_20210206_1039'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='onlinepaymentdetails',
        #     name='brand',
        #     field=models.CharField(blank=True, max_length=50, null=True),
        # ),
        # migrations.AddField(
        #     model_name='onlinepaymentdetails',
        #     name='cust_name',
        #     field=models.CharField(blank=True, max_length=50, null=True),
        # ),
        # migrations.AddField(
        #     model_name='onlinepaymentdetails',
        #     name='email',
        #     field=models.CharField(blank=True, max_length=50, null=True),
        # ),
        # migrations.AddField(
        #     model_name='onlinepaymentdetails',
        #     name='mobile',
        #     field=models.CharField(blank=True, max_length=50, null=True),
        # ),
    ]
