# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-06 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0039_auto_20210206_1256'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='onlinepaymentdetails',
        #     name='initiateResponse',
        #     field=models.CharField(blank=True, max_length=50, null=True),
        # ),
        # migrations.AddField(
        #     model_name='onlinepaymentdetails',
        #     name='is_failure',
        #     field=models.BooleanField(default=False),
        # ),
        # migrations.AddField(
        #     model_name='onlinepaymentdetails',
        #     name='successorfailureRes',
        #     field=models.TextField(blank=True, max_length=20000, null=True),
        # ),
    ]
