# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-06 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0040_auto_20210206_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinepaymentdetails',
            name='initiateResponse',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
