# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-08 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0041_auto_20210206_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='inMenu',
            field=models.BooleanField(default=True),
        ),
    ]
