# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-06 15:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0033_merge_20210205_1446'),
        ('ERP', '0041_auto_20210206_1345'),
    ]

    operations = [
    ]
