# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-02-06 14:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0034_auto_20210206_0554'),
        ('ERP', '0041_auto_20210206_1345'),
    ]

    operations = [
    ]
