# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-08 14:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0042_merge_20210206_1549'),
        ('ERP', '0042_application_inmenu'),
    ]

    operations = [
    ]
