# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-09 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0045_auto_20210209_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='appversioning',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
