# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-02-10 08:36
from __future__ import unicode_literals

import ERP.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0046_appversioning_title'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='AppVersioning',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('created', models.DateTimeField(auto_now_add=True)),
        #         ('minVersion', models.CharField(blank=True, max_length=50, null=True)),
        #         ('latestVersion', models.CharField(blank=True, max_length=50, null=True)),
        #         ('enabled', models.BooleanField(default=False)),
        #         ('title', models.CharField(blank=True, max_length=50, null=True)),
        #         ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='ERP.application')),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='MobileapplicationMedia',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('created', models.DateTimeField(auto_now_add=True)),
        #         ('typ', models.CharField(max_length=200, null=True)),
        #         ('attachment', models.FileField(null=True, upload_to=ERP.models.getappMediauploadPath)),
        #         ('app', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobileMedia', to='ERP.application')),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='OnlinePaymentDetails',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('created', models.DateTimeField(auto_now_add=True)),
        #         ('payId', models.CharField(blank=True, max_length=50, null=True)),
        #         ('amount', models.FloatField(default=0, null=True)),
        #         ('refId', models.CharField(blank=True, max_length=50, null=True)),
        #         ('paymentGatewayType', models.CharField(blank=True, max_length=50, null=True)),
        #         ('is_success', models.BooleanField(default=False)),
        #         ('source', models.CharField(blank=True, max_length=50, null=True)),
        #         ('chatUid', models.CharField(blank=True, max_length=50, null=True)),
        #         ('successUrl', models.CharField(blank=True, max_length=50, null=True)),
        #         ('failureUrl', models.CharField(blank=True, max_length=50, null=True)),
        #         ('email', models.CharField(blank=True, max_length=50, null=True)),
        #         ('cust_name', models.CharField(blank=True, max_length=50, null=True)),
        #         ('brand', models.CharField(blank=True, max_length=50, null=True)),
        #         ('mobile', models.CharField(blank=True, max_length=50, null=True)),
        #         ('initiateResponse', models.TextField(blank=True, max_length=10000, null=True)),
        #         ('successorfailureRes', models.TextField(blank=True, max_length=20000, null=True)),
        #         ('is_failure', models.BooleanField(default=False)),
        #     ],
        # ),
        # migrations.AddField(
        #     model_name='usagebilling',
        #     name='app',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usagebillings', to='ERP.application'),
        # ),
        # migrations.AddField(
        #     model_name='usagebilling',
        #     name='description',
        #     field=models.CharField(max_length=250, null=True),
        # ),
        # migrations.AddField(
        #     model_name='usagebilling',
        #     name='icon',
        #     field=models.CharField(max_length=250, null=True),
        # ),
    ]
