# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-02-10 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0048_auto_20210210_1125'),
        ('ERP', '0047_auto_20210210_1046'),
    ]

    operations = [
    ]
