# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-02-11 07:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0050_auto_20210211_0516'),
        ('ERP', '0050_auto_20210211_0641'),
    ]

    operations = [
    ]
