# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-02-12 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0051_merge_20210211_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='footerCss',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='division',
            name='headerCss',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
