# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-12 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0052_auto_20210212_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='chatIconPosition',
            field=models.TextField(default='right-bottom', max_length=20000),
        ),
    ]
