# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-16 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0054_division_freequotaexcceded'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='enterpriseSubscriptionReq',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
