# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-16 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0055_division_enterprisesubscriptionreq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='enterpriseSubscriptionReq',
            field=models.BooleanField(default=False),
        ),
    ]
