# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-18 06:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0057_auto_20210217_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(blank=True, max_length=50, null=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='divisionUsage', to='ERP.Division')),
            ],
        ),
    ]
