# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-18 07:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0058_usagetracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagetracker',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usagetracker',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
