# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-02-18 13:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0059_auto_20210218_0712'),
        ('ERP', '0058_auto_20210218_1250'),
    ]

    operations = [
    ]
