# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-22 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0060_merge_20210218_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.TextField(max_length=700),
        ),
    ]
