# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-02 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0061_auto_20210222_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='whatsapp_test_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
