# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-10 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0062_division_whatsapp_test_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='pageType',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
