# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-15 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0064_division_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='expenseData',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
