# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-03-22 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0065_division_expensedata'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='division',
        #     name='subscriptionExpiryDate',
        #     field=models.DateField(null=True),
        # ),
        # migrations.AlterField(
        #     model_name='onlinepaymentdetails',
        #     name='failureUrl',
        #     field=models.CharField(blank=True, max_length=200, null=True),
        # ),
    ]
