# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-03-25 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0067_auto_20210323_1407'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='division',
        #     name='subscriptionExpiryDate',
        #     field=models.DateField(null=True),
        # ),
        # migrations.AddField(
        #     model_name='application',
        #     name='totalRatings',
        #     field=models.FloatField(default=4.5, null=True),
        # ),
    ]
