# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-03-25 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0068_auto_20210325_0739'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='division',
        #     name='subscriptionExpiryDate',
        #     field=models.DateField(null=True),
        # ),
    ]
