# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-27 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0070_auto_20210325_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='totalRatings',
            field=models.FloatField(default=4.5, null=True),
        ),
    ]
