# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-03-27 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0071_auto_20210327_0511'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='division',
        #     name='enableWelcome',
        #     field=models.BooleanField(default=False),
        # ),
        # migrations.AddField(
        #     model_name='division',
        #     name='subscriptionExpiryDate',
        #     field=models.DateField(null=True),
        # ),
    ]
