# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-29 04:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0072_auto_20210327_1005'),
        ('ERP', '0072_auto_20210327_1140'),
    ]

    operations = [
    ]
