# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-29 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0073_merge_20210329_0435'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='division',
        #     name='enableWelcome',
        #     field=models.BooleanField(default=False),
        # ),
        # migrations.AddField(
        #     model_name='division',
        #     name='subscriptionExpiryDate',
        #     field=models.DateField(null=True),
        # ),
    ]
