# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-03-30 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0074_auto_20210329_0436'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='iosStoreUrl',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='macStoreUrl',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
