# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-03-30 07:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0075_auto_20210330_0716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='iosStoreUrl',
            new_name='windowsStoreUrl',
        ),
    ]
