# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-03-30 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0076_auto_20210330_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='richText',
            field=models.TextField(null=True),
        ),
    ]
