# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-30 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0077_application_richtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='unit',
            name='lng',
            field=models.FloatField(default=0),
        ),
    ]
