# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-03 08:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ERP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionIntentInputVariation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('uid', models.CharField(max_length=50)),
                ('page', models.TextField(max_length=550)),
                ('timeDuration', models.PositiveIntegerField(default=0)),
                ('reference', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callbackName', models.CharField(max_length=300, null=True)),
                ('condition', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(blank=True, max_length=5000, null=True)),
                ('url', models.CharField(max_length=100, null=True)),
                ('secondaryAnswer', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('terminate', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='ERP.Division')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relatedQuestions', to='chatbot.FAQ')),
            ],
        ),
        migrations.CreateModel(
            name='FAQInputVariation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt', models.CharField(max_length=500, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_vatiations', to='chatbot.FAQ')),
            ],
        ),
        migrations.CreateModel(
            name='NodeBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(max_length=3000, null=True)),
                ('auto_response', models.TextField(blank=True, max_length=3000, null=True)),
                ('context_key', models.CharField(blank=True, max_length=500, null=True)),
                ('rule', models.CharField(choices=[('process|extract|name', 'process|extract|name'), ('process|extract|mobile', 'process|extract|mobile'), ('process|extract|email', 'process|extract|email'), ('process|extract|date', 'process|extract|date'), ('process|extract|external', 'process|extract|external'), ('process|extract|rawText', 'process|extract|rawText'), ('process|reply', 'process|reply'), ('process|extract|custom', 'process|extract|custom'), ('process|extract|file', 'process|extract|file')], max_length=100, null=True)),
                ('type', models.CharField(choices=[('extract', 'extract'), ('process', 'process'), ('general', 'general'), ('product', 'product'), ('FAQ', 'FAQ')], max_length=50, null=True)),
                ('unique', models.BooleanField(default=False)),
                ('failResponse', models.TextField(blank=True, max_length=3000, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(max_length=3000, null=True)),
                ('requirementOrder', models.PositiveIntegerField(null=True)),
                ('nodeResponse', models.TextField(blank=True, max_length=1000, null=True)),
                ('externalProcessType', models.CharField(choices=[('RPA', 'RPA'), ('REST', 'REST'), ('APPOINTMENT', 'APPOINTMENT'), ('LEAD', 'LEAD'), ('EMAIL', 'EMAIL'), ('RESPONSE', 'RESPONSE')], max_length=100, null=True)),
                ('endpoint', models.CharField(max_length=100, null=True)),
                ('uipathEnvironment', models.CharField(max_length=100, null=True)),
                ('uipathProcess', models.CharField(max_length=100, null=True)),
                ('uipathRobot', models.CharField(max_length=1000, null=True)),
                ('uipathQueue', models.CharField(max_length=1000, null=True)),
                ('custom_process_code', models.TextField(max_length=5000, null=True)),
                ('verify', models.BooleanField(default=False)),
                ('pre_validation_code', models.TextField(blank=True, max_length=1000, null=True)),
                ('validation_code', models.TextField(blank=True, max_length=1000, null=True)),
                ('leadMagnet', models.BooleanField(default=False)),
                ('emailMagnet', models.BooleanField(default=False)),
                ('mobileMagnet', models.BooleanField(default=False)),
                ('nameMagnet', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
                ('leadMagnetDefer', models.PositiveIntegerField(default=2)),
                ('needConfirmation', models.BooleanField(default=False)),
                ('newx', models.FloatField(default=0, null=True)),
                ('newy', models.FloatField(default=0, null=True)),
                ('label', models.CharField(max_length=30, null=True)),
                ('icon', models.CharField(max_length=30, null=True)),
                ('color', models.CharField(max_length=30, null=True)),
                ('blockType', models.CharField(max_length=30, null=True)),
                ('exampleInput', models.CharField(max_length=500, null=True)),
                ('retry', models.PositiveIntegerField(default=0)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodeIntents', to='ERP.Division')),
                ('inheritedFrom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subClasses', to='chatbot.NodeBlock')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='context_requirement', to='chatbot.NodeBlock')),
            ],
        ),
        migrations.CreateModel(
            name='NodeBlockInputVariation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt', models.CharField(max_length=500, null=True)),
                ('response', models.TextField(max_length=500, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_vatiations', to='chatbot.NodeBlock')),
            ],
        ),
        migrations.CreateModel(
            name='NodeSlectionsVariations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt', models.CharField(max_length=500, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_variations_vatiations', to='chatbot.NodeBlock')),
            ],
        ),
        migrations.CreateModel(
            name='StartoverVariations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt', models.CharField(max_length=500, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startover_vatiations', to='chatbot.NodeBlock')),
            ],
        ),
        migrations.AddField(
            model_name='connection',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='chatbot.NodeBlock'),
        ),
        migrations.AddField(
            model_name='connection',
            name='to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connectionSources', to='chatbot.NodeBlock'),
        ),
        migrations.AddField(
            model_name='actionintentinputvariation',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_intent_vatiations', to='chatbot.NodeBlock'),
        ),
    ]
