# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-03 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariableContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, null=True)),
                ('value', models.CharField(max_length=500, null=True)),
                ('typ', models.CharField(max_length=10, null=True)),
                ('can_change', models.BooleanField(default=True)),
                ('nodeBlock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variableContexts', to='chatbot.NodeBlock')),
            ],
        ),
    ]
