# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-03 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_variablecontext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variablecontext',
            name='can_change',
            field=models.BooleanField(default=False),
        ),
    ]
