# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-03-27 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_auto_20210224_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodeblockinputvariation',
            name='init',
            field=models.BooleanField(default=False),
        ),
    ]
