# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-14 10:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gitweb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gitprofile',
            name='devices',
        ),
        migrations.RemoveField(
            model_name='gitprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='grouppermission',
            name='group',
        ),
        migrations.RemoveField(
            model_name='repo',
            name='groups',
        ),
        migrations.AddField(
            model_name='device',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gitdevices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='repopermission',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repoPermissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='GitProfile',
        ),
        migrations.DeleteModel(
            name='groupPermission',
        ),
    ]
