# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-03 08:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ERP', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.TextField(max_length=200, null=True)),
                ('serialNo', models.CharField(max_length=30, null=True)),
                ('warrantyTill', models.DateField(null=True)),
                ('manufacturedOn', models.DateField(null=True)),
                ('poNumber', models.CharField(max_length=20, null=True)),
                ('personName', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('address', models.TextField(max_length=1500, null=True)),
                ('assignedOn', models.DateTimeField(null=True)),
                ('returned', models.BooleanField(default=False)),
                ('returnComment', models.CharField(max_length=200, null=True)),
                ('checkout', models.BooleanField(default=False)),
                ('checkoutComment', models.TextField(max_length=300, null=True)),
                ('originalPrice', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
                ('reserved', models.BooleanField(default=False)),
                ('approvedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvedBy', to=settings.AUTH_USER_MODEL)),
                ('assignedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignedby', to=settings.AUTH_USER_MODEL)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='ERP.Division')),
                ('reservedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservedItems', to=settings.AUTH_USER_MODEL)),
                ('to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assetsAlloted', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='ERP.Unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assetsCheckedIn', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
