# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-05 05:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientRelationships', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('productName', models.TextField(max_length=400)),
                ('period', models.CharField(max_length=20)),
                ('totalServices', models.PositiveIntegerField(default=1)),
                ('serialNo', models.CharField(max_length=30)),
                ('notes', models.TextField(max_length=500)),
                ('seperateAddress', models.BooleanField(default=False)),
                ('installationAddress', models.TextField(max_length=300)),
                ('pincode', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('startDate', models.DateField(null=True)),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='clientRelationships.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('closedOn', models.DateTimeField(null=True)),
                ('preferredTimeSlot', models.CharField(max_length=20, null=True)),
                ('preferredDate', models.DateField(null=True)),
                ('name', models.CharField(max_length=150, null=True)),
                ('phone', models.CharField(max_length=150, null=True)),
                ('email', models.CharField(max_length=150, null=True)),
                ('productName', models.CharField(max_length=150, null=True)),
                ('productSerial', models.CharField(max_length=150, null=True)),
                ('warrantyStatus', models.CharField(max_length=150, null=True)),
                ('notes', models.TextField(max_length=850, null=True)),
                ('address', models.TextField(max_length=550, null=True)),
                ('pincode', models.CharField(max_length=150, null=True)),
                ('city', models.CharField(max_length=150, null=True)),
                ('state', models.CharField(max_length=150, null=True)),
                ('country', models.CharField(max_length=150, null=True)),
                ('requireOnSiteVisit', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('created', 'created'), ('assigned', 'assigned'), ('ongoing', 'ongoing'), ('completed', 'completed'), ('postponed', 'postponed'), ('cancelled', 'cancelled')], default='created', max_length=50)),
                ('postponeCount', models.PositiveIntegerField(default=0)),
                ('engineersNotes', models.TextField(max_length=850, null=True)),
                ('engineer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
                ('referenceAMC', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='clientRelationships.RegisteredProducts')),
                ('referenceContact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='clientRelationships.Contact')),
            ],
        ),
    ]
