# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-06 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0003_auto_20210106_0200'),
        ('clientRelationships', '0003_serviceticket_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='ERP.Division'),
        ),
    ]
