# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-06 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientRelationships', '0003_serviceticket_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceticket',
            name='serviceType',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
