# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-06 10:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientRelationships', '0004_serviceticket_servicetype'),
        ('clientRelationships', '0004_contract_division'),
    ]

    operations = [
    ]
