# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-06 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientRelationships', '0004_serviceticket_servicetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceticket',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('upcoming', 'upcoming'), ('assigned', 'assigned'), ('ongoing', 'ongoing'), ('completed', 'completed'), ('postponed', 'postponed'), ('cancelled', 'cancelled')], default='created', max_length=50),
        ),
    ]
