# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-06 12:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientRelationships', '0005_merge_20210106_1046'),
        ('clientRelationships', '0005_auto_20210106_1109'),
    ]

    operations = [
    ]
