# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-08 08:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0005_auto_20210107_1808'),
        ('clientRelationships', '0006_merge_20210106_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigureTermsAndConditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField(max_length=3000, null=True)),
                ('heading', models.TextField(max_length=100, null=True)),
                ('default', models.BooleanField(default=False)),
                ('division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='termsandconditions', to='ERP.Division')),
            ],
        ),
    ]
