# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-09 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientRelationships', '0008_auto_20210109_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='uniqueId',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
