# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-09 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientRelationships', '0009_contract_uniqueid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmtermsandconditions',
            name='counter',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
