# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-09 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientRelationships', '0010_auto_20210109_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmtermsandconditions',
            name='canInvoice',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='crmtermsandconditions',
            name='canSupplyOrder',
            field=models.BooleanField(default=False),
        ),
    ]
