# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-09 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientRelationships', '0011_auto_20210109_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuretermsandconditions',
            name='counter',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='configuretermsandconditions',
            name='prefix',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
