# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-09 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientRelationships', '0012_auto_20210109_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceticket',
            name='uniqueId',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
