# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-01-14 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientRelationships', '0013_serviceticket_uniqueid'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='typ',
            field=models.CharField(choices=[('b2b', 'b2b'), ('student', 'student')], default='b2b', max_length=50),
        ),
    ]
