# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-26 05:19
from __future__ import unicode_literals

import clientRelationships.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientRelationships', '0015_auto_20210121_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmtermsandconditions',
            name='logo',
            field=models.FileField(null=True, upload_to=clientRelationships.models.getClientRelationshipTerms),
        ),
    ]
