# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-08 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientRelationships', '0016_crmtermsandconditions_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='isFav',
            field=models.BooleanField(default=False),
        ),
    ]
