# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-22 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientRelationships', '0017_contact_isfav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='street',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
