# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-26 05:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0061_auto_20210222_0830'),
        ('clientRelationships', '0018_auto_20210222_0801'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('otp', models.CharField(blank=True, max_length=100, null=True)),
                ('token', models.CharField(blank=True, max_length=100, null=True)),
                ('expiryDate', models.DateTimeField(null=True)),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contactAuths', to='clientRelationships.Contact')),
                ('division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contactAuths', to='ERP.Division')),
            ],
        ),
    ]
