# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-19 07:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import forum.models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0011_merge_20210111_1745'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, null=True)),
                ('description', models.CharField(max_length=5000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('views', models.PositiveIntegerField(default=0)),
                ('url', models.CharField(max_length=150, null=True)),
                ('tags', models.CharField(max_length=150, null=True)),
                ('division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forumdivision', to='ERP.Division')),
            ],
        ),
        migrations.CreateModel(
            name='ForumCommentFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('attachment', models.FileField(null=True, upload_to=forum.models.forumCommentImages)),
                ('typ', models.CharField(default='image', max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ForumFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('attachment', models.FileField(null=True, upload_to=forum.models.forumImages)),
                ('typ', models.CharField(default='image', max_length=150, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='forumthread',
            name='user',
        ),
        migrations.RemoveField(
            model_name='forumcomment',
            name='txt',
        ),
        migrations.RemoveField(
            model_name='forumcomment',
            name='verified',
        ),
        migrations.AddField(
            model_name='forumcomment',
            name='anonymousEmail',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='forumcomment',
            name='anonymousName',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='forumcomment',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='forumcomment',
            name='content',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='forumcomment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='forumlikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='forumcomment',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forumparent', to='forum.Forum'),
        ),
        migrations.AlterField(
            model_name='forumcomment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forumusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ForumThread',
        ),
        migrations.AddField(
            model_name='forum',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='forumfiles', to='forum.ForumFiles'),
        ),
        migrations.AddField(
            model_name='forum',
            name='reporters',
            field=models.ManyToManyField(blank=True, related_name='forumreport', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forum',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forumuser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forumcomment',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='forumcommentfiles', to='forum.ForumCommentFiles'),
        ),
    ]
