# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-19 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0002_auto_20210111_0450'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='postCount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
