# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-20 09:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0003_profile_postcount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designation',
            name='apps',
        ),
    ]
