# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-25 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0004_remove_designation_apps'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='isOnSupport',
            field=models.BooleanField(default=False),
        ),
    ]
