# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-03-23 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0006_profile_laststate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designations', to='ERP.Division'),
        ),
    ]
