# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-26 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0008_auto_20210414_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='newReg',
            field=models.BooleanField(default=False),
        ),
    ]
