# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-27 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0009_profile_newreg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='newReg',
            field=models.BooleanField(default=True),
        ),
    ]
