# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-04 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0010_auto_20210427_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='newReg',
            field=models.BooleanField(default=False),
        ),
    ]
