# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-12 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0011_auto_20210504_0423'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='countryCode',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='lang',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
