# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-03 08:22
from __future__ import unicode_literals

import PIM.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ERP', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', models.TextField(choices=[(b'personal', b'personal'), (b'public', b'public'), (b'management', b'management'), (b'friends', b'friends')], default=b'personal', max_length=20)),
                ('eventType', models.TextField(choices=[(b'Meeting', b'Meeting'), (b'Reminder', b'Reminder'), (b'ToDo', b'ToDo'), (b'EVENT', b'EVENT'), (b'Deadline', b'Deadline'), (b'Other', b'Other')], default=b'Other', max_length=11)),
                ('originator', models.TextField(max_length=20, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(max_length=200, null=True)),
                ('when', models.DateTimeField(null=True)),
                ('duration', models.IntegerField(null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('canceled', models.BooleanField(default=False)),
                ('level', models.TextField(choices=[(b'Normal', b'Normal'), (b'Critical', b'Critical'), (b'Optional', b'Optional'), (b'Mandatory', b'Mandatory')], default=b'Normal', max_length=10)),
                ('venue', models.TextField(max_length=50, null=True)),
                ('attachment', models.FileField(null=True, upload_to=PIM.models.getCalendarAttachment)),
                ('myNotes', models.TextField(blank=True, max_length=100)),
                ('data', models.TextField(max_length=200, null=True)),
                ('followers', models.ManyToManyField(blank=True, related_name='calendarItemsFollowing', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('uid', models.CharField(max_length=50, null=True)),
                ('attachment', models.FileField(null=True, upload_to=PIM.models.getSupportChatAttachment)),
                ('message', models.TextField(max_length=5000, null=True)),
                ('attachmentType', models.CharField(max_length=50, null=True)),
                ('sentByAgent', models.BooleanField(default=False)),
                ('responseTime', models.FloatField(blank=True, null=True)),
                ('logs', models.CharField(blank=True, max_length=500, null=True)),
                ('delivered', models.BooleanField(default=False)),
                ('read', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('fileType', models.TextField(max_length=10, null=True)),
                ('fileSize', models.TextField(max_length=10, null=True)),
                ('fileName', models.TextField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatThread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=40, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('dp', models.FileField(null=True, upload_to=PIM.models.getChatThreadDP)),
                ('lastActivity', models.DateTimeField(blank=True, null=True)),
                ('isLate', models.BooleanField(default=False)),
                ('uid', models.CharField(max_length=50, null=True, unique=True)),
                ('status', models.CharField(choices=[(b'started', b'started'), (b'closed', b'closed'), (b'reviewed', b'reviewed'), (b'resolved', b'resolved'), (b'archived', b'archived'), (b'escalatedL1', b'escalatedL1'), (b'escalatedL2', b'escalatedL2'), (b'missed', b'missed')], default=b'started', max_length=15)),
                ('customerRating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('customerFeedback', models.CharField(blank=True, max_length=3000, null=True)),
                ('userDevice', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=5000, null=True)),
                ('userDeviceIp', models.CharField(blank=True, max_length=100, null=True)),
                ('firstResponseTime', models.FloatField(blank=True, null=True)),
                ('typ', models.CharField(blank=True, max_length=100, null=True)),
                ('userAssignedTime', models.DateTimeField(blank=True, null=True)),
                ('firstMessage', models.TextField(blank=True, max_length=2000, null=True)),
                ('channel', models.CharField(choices=[(b'self', b'self'), (b'FB', b'FB')], default=b'self', max_length=50)),
                ('transferred', models.BooleanField(default=False)),
                ('fid', models.CharField(max_length=50, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatThread', to='ERP.Division')),
                ('participants', models.ManyToManyField(blank=True, related_name='chat_threads', to=settings.AUTH_USER_MODEL)),
                ('receivedBy', models.ManyToManyField(blank=True, related_name='receivedBy', to=settings.AUTH_USER_MODEL)),
                ('visitor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chatThreads', to='marketing.Contacts')),
            ],
        ),
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(max_length=300, null=True)),
                ('link', models.URLField(max_length=100, null=True)),
                ('title', models.TextField(max_length=250, null=True)),
                ('read', models.BooleanField(default=False)),
                ('domain', models.TextField(choices=[(b'System', b'System'), (b'Administration', b'Administration'), (b'Application', b'Application')], default=b'System', max_length=250)),
                ('onHold', models.BooleanField(default=False)),
                ('broadcast', models.BooleanField(default=False)),
                ('orginatedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generatedNotifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presence', models.TextField(choices=[(b'NA', b'NA'), (b'Available', b'Available'), (b'Busy', b'Busy'), (b'Away', b'Away'), (b'On Leave', b'On Leave'), (b'In A Meeting', b'In a meeting')], default=b'NA', max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main', models.TextField(max_length=10, null=True)),
                ('highlight', models.TextField(max_length=10, null=True)),
                ('background', models.TextField(max_length=10, null=True)),
                ('backgroundImg', models.ImageField(null=True, upload_to=PIM.models.getThemeImageUploadPath)),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme', to='PIM.settings')),
            ],
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='thread',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='PIM.ChatThread'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supportFile', to=settings.AUTH_USER_MODEL),
        ),
    ]
