# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-04 14:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PIM', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatthread',
            name='closedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='closedUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatthread',
            name='closedOn',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
