# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-04 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PIM', '0002_auto_20210104_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50, null=True)),
                ('key', models.CharField(max_length=50, null=True)),
                ('value', models.CharField(max_length=500, null=True)),
                ('typ', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
