# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-01-07 11:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PIM', '0003_chatcontext'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatthread',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='externalChatThreads', to=settings.AUTH_USER_MODEL),
        ),
    ]
