# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-22 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PIM', '0004_chatthread_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_personal',
            field=models.BooleanField(default=False),
        ),
    ]
