# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-22 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PIM', '0005_chatmessage_is_personal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='is_personal',
        ),
        migrations.AddField(
            model_name='chatthread',
            name='is_personal',
            field=models.BooleanField(default=False),
        ),
    ]
