# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-22 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PIM', '0006_auto_20210122_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatthread',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chatThread', to='ERP.Division'),
        ),
    ]
