# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-23 07:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PIM', '0007_auto_20210122_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='replyTo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='PIM.ChatMessage'),
        ),
    ]
