# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-27 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PIM', '0008_chatmessage_replyto'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_forwarded',
            field=models.BooleanField(default=False),
        ),
    ]
