# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-28 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PIM', '0009_chatmessage_is_forwarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='end',
            field=models.DateTimeField(null=True),
        ),
    ]
