# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-29 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PIM', '0010_calendar_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='zoomcode',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
