# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-27 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PIM', '0015_calendar_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatthread',
            name='participantscount',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
