# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-02-01 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0026_auto_20210201_1232'),
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marketingcontacts', to='ERP.Division'),
        ),
    ]
