# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-23 12:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0077_application_richtext'),
        ('marketing', '0002_contacts_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='ERP.Division'),
        ),
        migrations.AddField(
            model_name='campaigntracker',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_trackers', to='ERP.Division'),
        ),
        migrations.AddField(
            model_name='tourplan',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tour_plans', to='ERP.Division'),
        ),
        migrations.AlterField(
            model_name='tourplanstop',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tour_plan_stops', to='ERP.Division'),
        ),
    ]
