# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-29 04:41
from __future__ import unicode_literals

import RPA.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ERP', '0074_auto_20210329_0436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('retryCount', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('queued', 'queued'), ('started', 'started'), ('failed', 'failed'), ('success', 'success'), ('aborted', 'aborted')], default='queued', max_length=50)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rpa_jobs', to='ERP.Division')),
            ],
        ),
        migrations.CreateModel(
            name='JobContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=50, null=True)),
                ('value', models.CharField(max_length=500, null=True)),
                ('attachment', models.FileField(null=True, upload_to=RPA.models.getContextAttachment)),
                ('typ', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('info', 'info'), ('error', 'error'), ('warn', 'warn')], default='info', max_length=50)),
                ('data', models.TextField(max_length=20000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('uri', models.CharField(max_length=200)),
                ('argSchema', models.TextField(max_length=20000, null=True)),
                ('env', models.CharField(max_length=200)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rpa_processes', to='ERP.Division')),
            ],
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rpa_queues', to='ERP.Division')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queues', to='RPA.Process')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='queue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='RPA.Queue'),
        ),
    ]
