# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-03-30 09:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RPA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='process',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processjobs', to='RPA.Process'),
        ),
    ]
