# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-19 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0077_application_richtext'),
        ('RPA', '0003_auto_20210419_0802'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('key', models.CharField(max_length=200)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rpa_machine', to='ERP.Division')),
            ],
        ),
    ]
