# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-19 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPA', '0004_machine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='key',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
