# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-20 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPA', '0005_auto_20210419_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='env',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
