# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-20 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RPA', '0006_machine_env'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rpa_jobs', to='RPA.Machine'),
        ),
    ]
