# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-03 08:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('feed', models.TextField(max_length=500, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbackUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(null=True)),
                ('approved', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('created', 'created'), ('saved', 'saved'), ('submitted', 'submitted'), ('approved', 'approved')], default='created', max_length=10, null=True)),
                ('checkIn', models.DateTimeField(null=True)),
                ('checkOut', models.DateTimeField(null=True)),
                ('totaltime', models.CharField(max_length=30, null=True)),
                ('checkinLat', models.FloatField(default=0)),
                ('checkinLon', models.FloatField(default=0)),
                ('checkoutLat', models.FloatField(default=0)),
                ('checkoutLon', models.FloatField(default=0)),
                ('distanceTravelled', models.FloatField(default=0)),
                ('approvedBy', models.ManyToManyField(blank=True, related_name='times', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeSheetCreated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='timesheet',
            unique_together=set([('user', 'date')]),
        ),
    ]
