# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-30 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='attendance_status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Leave', 'Leave'), ('Half-Day', 'Half-Day')], default='Absent', max_length=10, null=True),
        ),
    ]
