# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-01-07 05:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ERP', '0003_auto_20210106_0200'),
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='page',
            name='user',
        ),
        migrations.AddField(
            model_name='notebook',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='ERP.Division'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notebook',
            name='shares',
            field=models.ManyToManyField(blank=True, related_name='sharedNotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notebook',
            name='source',
            field=models.TextField(max_length=1000000, null=True),
        ),
        migrations.AddField(
            model_name='notebook',
            name='type',
            field=models.CharField(choices=[('private', 'private'), ('public', 'public')], default=None, max_length=40),
        ),
        migrations.DeleteModel(
            name='page',
        ),
    ]
