# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-01-07 06:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20210107_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notebooks', to=settings.AUTH_USER_MODEL),
        ),
    ]
