# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-01-07 06:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20210107_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='ERP.Division'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='type',
            field=models.CharField(choices=[('private', 'private'), ('public', 'public')], max_length=40),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notebooks', to=settings.AUTH_USER_MODEL),
        ),
    ]
