# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-03-30 06:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_project_notes'),
        ('notes', '0005_auto_20210107_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectnotebook', to='projects.project'),
        ),
    ]
