# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-04-22 08:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_notebook_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notebook', to='notes.notebook'),
        ),
    ]
