# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-03 08:22
from __future__ import unicode_literals

import LMS.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=2000, null=True)),
                ('dp', models.FileField(null=True, upload_to=LMS.models.getCourseDPAttachmentPath)),
                ('author', models.CharField(max_length=100, null=True)),
                ('ISSN', models.CharField(max_length=100, null=True)),
                ('volume', models.CharField(max_length=100, null=True)),
                ('version', models.CharField(max_length=100, null=True)),
                ('license', models.CharField(max_length=100, null=True)),
                ('topic', models.CharField(max_length=200, null=True)),
                ('subject', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('enrollmentStatus', models.CharField(choices=[('open', 'open'), ('onInvitation', 'onInvitation'), ('admin', 'admin'), ('onRequest', 'onRequest'), ('closed', 'closed')], default='pdf', max_length=20)),
                ('description', models.TextField(max_length=2000)),
                ('dp', models.FileField(null=True, upload_to=LMS.models.getCourseDPAttachmentPath)),
                ('urlSuffix', models.CharField(max_length=100, null=True)),
                ('sellingPrice', models.CharField(max_length=100, null=True)),
                ('discount', models.CharField(max_length=100, null=True)),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lmsCoursesInstructing', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courseCreated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseActivty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('attachment', models.FileField(null=True, upload_to=LMS.models.getVideoPath)),
                ('thumbnail', models.ImageField(null=True, upload_to=LMS.models.getVideoThumbnailPath)),
                ('typ', models.CharField(choices=[('video', 'video'), ('notes', 'notes'), ('file', 'file'), ('homework', 'homework'), ('quiz', 'quiz')], max_length=10, null=True)),
                ('paperDueDate', models.DateField(null=True)),
                ('time', models.DateTimeField(null=True)),
                ('venue', models.CharField(max_length=100, null=True)),
                ('txt', models.TextField(null=True)),
                ('meetingId', models.CharField(max_length=100, null=True)),
                ('date', models.DateTimeField(null=True)),
                ('announcer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('accepted', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('addedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lmsUsersAdded', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='LMS.Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OptionsPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('text', 'text'), ('image', 'image')], default='text', max_length=10)),
                ('rtxt', models.TextField(max_length=2000, null=True)),
                ('image', models.FileField(null=True, upload_to=LMS.models.getQAttachmentPath)),
                ('sequence', models.PositiveIntegerField(null=True)),
                ('answer', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('timelimit', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papersAuthored', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('text', 'text'), ('image', 'image')], default='text', max_length=10)),
                ('txt', models.TextField(max_length=2000, null=True)),
                ('image', models.FileField(null=True, upload_to=LMS.models.getQAttachmentPath)),
                ('sequence', models.PositiveIntegerField(null=True)),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('qtype', models.CharField(choices=[('mcq', 'Single Correct Choice'), ('mcc', 'Multiple Correct Choices'), ('code', 'Code'), ('upload', 'Assignment Upload'), ('integer', 'Answer in Integer'), ('string', 'Answer in String'), ('float', 'Answer in Float')], default='mcq', max_length=10)),
                ('ques', models.TextField(max_length=5000)),
                ('marks', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('sequence', models.PositiveIntegerField(null=True)),
                ('shortUrl', models.CharField(max_length=100, null=True, unique=True)),
                ('description', models.TextField(max_length=2000, null=True)),
                ('seoTitle', models.CharField(max_length=100, null=True, unique=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='LMS.Book')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='bookSection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='LMS.Section'),
        ),
        migrations.AddField(
            model_name='question',
            name='paper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='LMS.Paper'),
        ),
        migrations.AddField(
            model_name='qpart',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='LMS.Question'),
        ),
        migrations.AddField(
            model_name='optionspart',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='LMS.Question'),
        ),
        migrations.AddField(
            model_name='courseactivty',
            name='paper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homeworkPaper', to='LMS.Paper'),
        ),
    ]
