# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-01-12 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientRelationships', '0013_serviceticket_uniqueid'),
        ('LMS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='contacts',
            field=models.ManyToManyField(related_name='students', to='clientRelationships.Contact'),
        ),
    ]
