# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-01-12 09:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0002_course_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseactivty',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courseActivities', to='LMS.Course'),
        ),
    ]
