# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-01-12 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0003_courseactivty_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseactivty',
            name='time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
