# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-01-12 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0004_auto_20210112_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseactivty',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='courseactivty',
            name='title',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='LMS.Section'),
        ),
    ]
