# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-01-14 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0005_auto_20210112_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='shortUrl',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
