# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-01-14 07:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0006_book_shorturl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='bookSection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionss', to='LMS.Section'),
        ),
    ]
