# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-01-15 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0007_auto_20210114_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='isLatex',
            field=models.BooleanField(default=False),
        ),
    ]
