# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-01-15 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0009_course_activecourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
