# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-01-15 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientRelationships', '0014_contact_typ'),
        ('LMS', '0010_auto_20210115_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='contacts',
            field=models.ManyToManyField(related_name='papers', to='clientRelationships.Contact'),
        ),
    ]
