# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-01-18 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0011_paper_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='topic',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
