# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-01-18 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0012_course_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='enrollmentStatus',
            field=models.CharField(choices=[('open', 'open'), ('onInvitation', 'onInvitation'), ('admin', 'admin'), ('onRequest', 'onRequest'), ('closed', 'closed')], default='open', max_length=20),
        ),
    ]
