# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-01-21 08:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0013_auto_20210118_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseactivty',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activitychildren', to='LMS.CourseActivty'),
        ),
        migrations.AlterField(
            model_name='courseactivty',
            name='typ',
            field=models.CharField(choices=[('video', 'video'), ('notes', 'notes'), ('file', 'file'), ('homework', 'homework'), ('quiz', 'quiz'), ('class', 'class')], max_length=10, null=True),
        ),
    ]
