# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-01-21 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0014_auto_20210121_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseactivty',
            name='daily',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courseactivty',
            name='monthly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courseactivty',
            name='weekly',
            field=models.BooleanField(default=False),
        ),
    ]
