# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-01-21 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0015_auto_20210121_0835'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='courseactivty',
        #     name='time',
        #     field=models.DateTimeField(null=True),
        # ),
    ]
