# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-01-22 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0016_auto_20210121_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseactivty',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
