# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-23 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0017_auto_20210122_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseactivty',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
