# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-28 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0021_auto_20210127_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseactivty',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
