# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-02-01 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0027_auto_20210201_1232'),
        ('LMS', '0026_auto_20210201_0646'),
    ]

    operations = [
    ]
