# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-02-05 15:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0033_auto_20210205_0946'),
        ('LMS', '0032_auto_20210204_1538'),
    ]

    operations = [
    ]
