# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-06 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0034_merge_20210205_1503'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='enrollment',
        #     name='accepted',
        # ),
        # migrations.AddField(
        #     model_name='enrollment',
        #     name='amountPaid',
        #     field=models.PositiveIntegerField(default=0),
        # ),
        # migrations.AddField(
        #     model_name='enrollment',
        #     name='amountPending',
        #     field=models.PositiveIntegerField(default=0),
        # ),
    ]
