# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-02-06 14:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0035_auto_20210206_0554'),
        ('LMS', '0035_auto_20210206_0824'),
    ]

    operations = [
    ]
