# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-02-10 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0040_auto_20210210_1125'),
        ('LMS', '0039_auto_20210210_1034'),
    ]

    operations = [
    ]
