# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-10 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0063_division_pagetype'),
        ('LMS', '0043_merge_20210211_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coursesdivision', to='ERP.Division'),
        ),
    ]
