# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-11 09:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0063_division_pagetype'),
        ('LMS', '0044_course_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookDivision', to='ERP.Division'),
        ),
        migrations.AddField(
            model_name='paper',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paperDivision', to='ERP.Division'),
        ),
    ]
