# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-01-11 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskBoard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='mediaType',
            field=models.CharField(choices=[('onlineVideo', 'onlineVideo'), ('video', 'video'), ('image', 'image'), ('onlineImage', 'onlineImage'), ('doc', 'doc'), ('excel', 'excel'), ('ppt', 'ppt'), ('pdf', 'pdf')], default='image', max_length=10),
        ),
    ]
