# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-11 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='alCurrMonthLeaves',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='mlCurrMonthLeaves',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
