# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-12 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_auto_20210111_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advances',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='advances',
            name='approvers',
        ),
        migrations.RemoveField(
            model_name='advances',
            name='disbursed',
        ),
        migrations.RemoveField(
            model_name='advances',
            name='emi',
        ),
        migrations.RemoveField(
            model_name='advances',
            name='emiStartOffset',
        ),
        migrations.RemoveField(
            model_name='advances',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='advances',
            name='invoiceAmt',
        ),
        migrations.RemoveField(
            model_name='advances',
            name='loanStarted',
        ),
        migrations.RemoveField(
            model_name='advances',
            name='loanStartedDate',
        ),
        migrations.RemoveField(
            model_name='advances',
            name='modeOfReturn',
        ),
        migrations.RemoveField(
            model_name='advances',
            name='referenceNumber',
        ),
        migrations.RemoveField(
            model_name='advances',
            name='returnBalance',
        ),
        migrations.RemoveField(
            model_name='advances',
            name='settlementDate',
        ),
        migrations.RemoveField(
            model_name='advances',
            name='settlementUser',
        ),
        migrations.RemoveField(
            model_name='advances',
            name='tenure',
        ),
        migrations.RemoveField(
            model_name='advances',
            name='typ',
        ),
        migrations.AddField(
            model_name='advances',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='advances',
            name='returnMethod',
            field=models.CharField(choices=[('SALARY_ADVANCE', 'SALARY_ADVANCE'), ('PROJECT_ADVANCE', 'PPROJECT_ADVANCE')], default='SALARY_ADVANCE', max_length=30),
        ),
        migrations.AlterField(
            model_name='advances',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
