# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-12 06:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0011_merge_20210111_1745'),
        ('payroll', '0004_auto_20210112_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='advances',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advances', to='ERP.Division'),
        ),
    ]
