# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-12 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_advances_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='advanceIds',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
