# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-12 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_payslip_advanceids'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='advanceDeduction',
            field=models.FloatField(default=0),
        ),
    ]
