# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-12 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_payslip_advancededuction'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='isExtraIncome',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payroll',
            name='isOwnHouse',
            field=models.BooleanField(default=False),
        ),
    ]
