# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-20 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0008_auto_20210112_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='isRentedHouse',
            field=models.BooleanField(default=False),
        ),
    ]
