# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-22 12:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0061_auto_20210222_0830'),
        ('payroll', '0009_payroll_isrentedhouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollreport',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payrolldivision', to='ERP.Division'),
        ),
        migrations.AlterUniqueTogether(
            name='payrollreport',
            unique_together=set([('year', 'month', 'division')]),
        ),
    ]
