# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-22 13:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0061_auto_20210222_0830'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payroll', '0010_auto_20210222_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payslipdivision', to='ERP.Division'),
        ),
        migrations.AlterUniqueTogether(
            name='payslip',
            unique_together=set([('year', 'month', 'user', 'division')]),
        ),
    ]
