# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-03 08:22
from __future__ import unicode_literals

import blogging.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=1000)),
                ('articleUrl', models.CharField(max_length=1000)),
                ('lang', models.CharField(choices=[('hi', 'hi'), ('en', 'en')], default='hi', max_length=20)),
                ('publishingChannel', models.CharField(max_length=50, null=True)),
                ('featuredContent', models.BooleanField(default=False)),
                ('sensitive', models.BooleanField(default=False)),
                ('scheduleTime', models.DateTimeField()),
                ('published', models.BooleanField(default=False)),
                ('summary', models.TextField(blank=True, max_length=5000, null=True)),
                ('tags', models.TextField(blank=True, max_length=1000, null=True)),
                ('metaTitle', models.CharField(max_length=1000)),
                ('metaDescription', models.CharField(blank=True, max_length=5000, null=True)),
                ('keywords', models.TextField(blank=True, max_length=1000, null=True)),
                ('qb1', models.CharField(blank=True, max_length=700, null=True)),
                ('qb2', models.CharField(blank=True, max_length=700, null=True)),
                ('qb3', models.CharField(blank=True, max_length=700, null=True)),
                ('qb4', models.CharField(blank=True, max_length=700, null=True)),
                ('qb5', models.CharField(blank=True, max_length=700, null=True)),
                ('qb6', models.CharField(blank=True, max_length=700, null=True)),
                ('qb7', models.CharField(blank=True, max_length=700, null=True)),
                ('content_type', models.CharField(max_length=10, null=True)),
                ('reviewDatetime', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('created', 'created'), ('reviewed', 'reviewed'), ('published', 'published'), ('archived', 'archived'), ('submitted', 'submitted')], default='created', max_length=20)),
                ('read_time', models.PositiveIntegerField(blank=True, null=True)),
                ('ogImg', models.ImageField(null=True, upload_to=blogging.models.getArticleImagePath)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articlesWritten', to=settings.AUTH_USER_MODEL)),
                ('contentWriter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('header', models.TextField(max_length=700, null=True)),
                ('shortTitle', models.TextField(max_length=700, null=True)),
                ('content', models.TextField(max_length=20000, null=True)),
                ('content_text', models.TextField(max_length=20000, null=True)),
                ('img', models.ImageField(null=True, upload_to=blogging.models.getSectionImagePath)),
                ('altTexts', models.CharField(max_length=1000, null=True)),
                ('link', models.CharField(max_length=200, null=True)),
                ('typ', models.CharField(choices=[('html', 'html'), ('image', 'image'), ('video', 'video')], default='html', max_length=20)),
                ('imageTitle', models.CharField(max_length=200, null=True)),
                ('index', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('index',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('txt', models.CharField(max_length=1000, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=250, null=True)),
                ('email', models.CharField(max_length=250, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogging.Article')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InternalComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articlesReviewComment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='contents',
            field=models.ManyToManyField(blank=True, to='blogging.ArticleSection'),
        ),
        migrations.AddField(
            model_name='article',
            name='reviewComments',
            field=models.ManyToManyField(blank=True, to='blogging.InternalComment'),
        ),
        migrations.AddField(
            model_name='article',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articlesReviewed', to=settings.AUTH_USER_MODEL),
        ),
    ]
