# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-20 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0003_article_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
