# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-03 08:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivePatient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inTime', models.DateTimeField(null=True)),
                ('outTime', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('checkedIn', 'checkedIn'), ('onGoingTreatment', 'onGoingTreatment'), ('operation', 'operation'), ('observation', 'observation'), ('readyToDischarged', 'readyToDischarged'), ('dishcharged', 'dishcharged'), ('settled', 'settled')], default='checkedIn', max_length=100)),
                ('outPatient', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('dateOfDischarge', models.DateTimeField(blank=True, null=True)),
                ('mlc', models.BooleanField(default=False)),
                ('cash', models.BooleanField(default=False)),
                ('insurance', models.BooleanField(default=False)),
                ('opNo', models.CharField(blank=True, max_length=100, null=True)),
                ('msg', models.CharField(blank=True, default='Thank You', max_length=100, null=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='DischargeSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipNo', models.CharField(blank=True, max_length=100, null=True)),
                ('mlcNo', models.CharField(blank=True, default='', max_length=100)),
                ('firNo', models.CharField(blank=True, default='', max_length=100)),
                ('provisionalDiagnosis', models.TextField(blank=True, default='', max_length=4000)),
                ('finalDiagnosis', models.TextField(blank=True, default='', max_length=4000)),
                ('complaintsAndReason', models.TextField(blank=True, default='', max_length=4000)),
                ('summIllness', models.TextField(blank=True, default='', max_length=4000)),
                ('keyFindings', models.TextField(blank=True, default='', max_length=4000)),
                ('historyOfAlchohol', models.TextField(blank=True, default='', max_length=4000)),
                ('pastHistory', models.TextField(blank=True, default='', max_length=4000)),
                ('familyHistory', models.TextField(blank=True, default='', max_length=4000)),
                ('summaryKeyInvestigation', models.TextField(blank=True, default='', max_length=4000)),
                ('courseInHospital', models.TextField(blank=True, default='', max_length=4000)),
                ('patientCondition', models.TextField(blank=True, default='', max_length=4000)),
                ('advice', models.TextField(blank=True, default='', max_length=4000)),
                ('reviewOn', models.TextField(blank=True, default='', max_length=4000)),
                ('complications', models.TextField(blank=True, default='', max_length=4000)),
                ('treatmentGiven', models.TextField(blank=True, default='', max_length=4000)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dischargeSummary', to='hospitalManagement.ActivePatient')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('invoiceName', models.CharField(max_length=20, null=True)),
                ('grandTotal', models.PositiveIntegerField(default=0, null=True)),
                ('quantity', models.CharField(default=1, max_length=100)),
                ('products', models.CharField(max_length=10000, null=True)),
                ('billed', models.BooleanField(default=False)),
                ('discount', models.PositiveIntegerField(default=0)),
                ('activePatient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='hospitalManagement.ActivePatient')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, max_length=100)),
                ('dateOfBirth', models.DateField(null=True)),
                ('age', models.CharField(max_length=150, null=True)),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('phoneNo', models.CharField(max_length=100)),
                ('emergencyContact1', models.CharField(max_length=100, null=True)),
                ('emergencyContact2', models.CharField(max_length=100, null=True)),
                ('street', models.TextField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=15, null=True)),
                ('pin', models.IntegerField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, default='India', max_length=20, null=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='PatientComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('data', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='hospitalManagement.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('rate', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='treatingConsultant',
            field=models.ManyToManyField(related_name='patients', to='hospitalManagement.Doctor'),
        ),
        migrations.AddField(
            model_name='activepatient',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='inPatientComments', to='hospitalManagement.PatientComments'),
        ),
        migrations.AddField(
            model_name='activepatient',
            name='docName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primaryDoctor', to='hospitalManagement.Doctor'),
        ),
        migrations.AddField(
            model_name='activepatient',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patientIn', to='hospitalManagement.Patient'),
        ),
    ]
