# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-01-05 06:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0001_initial'),
        ('hospitalManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='ERP.Division'),
        ),
        migrations.AddField(
            model_name='patient',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='ERP.Division'),
        ),
        migrations.AddField(
            model_name='product',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='ERP.Division'),
        ),
    ]
