# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-11 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalManagement', '0002_auto_20210105_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='activepatient',
            name='inBillNo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='activepatient',
            name='inPatientId',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='activepatient',
            name='outBillNo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='activepatient',
            name='outPatientId',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
