# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-11 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalManagement', '0003_auto_20210111_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activepatient',
            name='inPatientId',
        ),
        migrations.RemoveField(
            model_name='activepatient',
            name='outPatientId',
        ),
    ]
