# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-11 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalManagement', '0004_auto_20210111_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activepatient',
            name='inBillNo',
        ),
        migrations.RemoveField(
            model_name='activepatient',
            name='outBillNo',
        ),
        migrations.AddField(
            model_name='invoice',
            name='billNo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
